### ISSUE TITLE
Youtube host file

### ISSUE THREAD

**Issue by nvg123** [franklai/synologyhost#1]
Hi, 

Looks like there are some updates on YouTube. Host file fails to download video. Please, fix if possible, Thank you in advance.
![20201229_190534_578](https://user-images.githubusercontent.com/59006253/103297187-dc3b4e00-4a08-11eb-8188-95f13d294571.png)

**Comment by franklai** [comment]
v1.14 is available now

https://github.com/franklai/synologyhost/releases/tag/youtube-1.14

**Comment by nvg123** [comment]
Thank you very much! Woks perfect!
