### ISSUE TITLE
Youtube host file (1.15) broken

### ISSUE THREAD

**Issue by nvg123** [franklai/synologyhost#2]
Hi,

Sorry for bothering again. Looks like host is broken again.
Sample video id: 046FZ38gchg

Thanks.

**Comment by franklai** [comment]
@nvg123 YouTube host 1.15 tested ok on my DS (dsm 6.2.3 + Download Station 3.8.16)

What's your DSM version and Download Station version?

**Comment by nvg123** [comment]
Hi,

Yes, seems to be local issues. Updated DSM to latest, rebooted and the problem disappeared.
Sorry for disturbing you.

**Comment by nvg123** [comment]
Looks like I found the difference. My synology is connected to internet via VPN in Europe. If I enable VPN on PC, then I see the following before can access Youtube.

![image](https://user-images.githubusercontent.com/59006253/113739225-40586700-9708-11eb-8590-beaabb6fe242.png)

If I disable VPN, I can download videos. So, the solution is to disable VPN or find server on another location, like US or Canada )

**Comment by franklai** [comment]
Thanks for the information!
