### ISSUE TITLE
error downloading

### ISSUE THREAD

**Issue by potsso** [franklai/synologyhost#3]
Hi fanklai

i was using download station with no problem just last week. tried again today and no joy.

i actually tried a few vids i know worked. this week no joy though.

any suggestions would be appreciated. 

download station 3.8.16.3566
DSM 6.2.4-25556

video below.

Thanks

https://www.youtube.com/watch?v=xJYfOGb3sKw&t=6s&ab_channel=siamesepuppy

**Comment by potsso** [comment]
could running an old version of pearl be a problem? 

I'm running 5.24.0.0074 as the new version stops logitech media server working.

**Comment by franklai** [comment]
Hi @potsso 

I can download the link without problem.

We got report in [https://github.com/franklai/synologyhost/issues/2#issuecomment-814227825](https://github.com/franklai/synologyhost/issues/2#issuecomment-814227825) that network in Europe will get a different page before accessing YouTube. Is this the case?

**Comment by franklai** [comment]
no feedback. close it
